language: java

jdk:
- oraclejdk7
- oraclejdk8

script: mvn clean install

deploy:
  provider: bintray
  file: bintray.config
  user: jenzz
  key:
    secure: lIwOeiy+h1UCtE9kyWx7sfP7xOto+K8T5ZN+F6mg3gJ//MwZO9cuqm39OZgmqxLDk8JPY48z/KOQ7JMTtFUYk70WfwFcH8VyA2QdJfRUJjDGDYew7v1BSRnrcCuabea+p1chp7VImZTpGnaD7rD5Ric2skYr3CYYD1aqMIjKWHw=
#  passphrase: Optional. In case a passphrase is configured on Bintray and GPG signing is used